#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - identity
    - network
  identity:
    hostname: ubuntu-desktop
    username: ubuntu
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
  locale: en_US.UTF-8
  keyboard:
    layout: us
  network:
    version: 2
    ethernets:
      any-eth:
        match:
          name: "en*"
        dhcp4: true
        dhcp6: true
        optional: true
    wifis:
      any-wifi:
        match:
          name: "wl*"
        dhcp4: true
        dhcp6: true
        optional: true
  ssh:
    install-server: true
    allow-pw: true
  source:
    id: ubuntu-desktop
    search_drivers: true
  shutdown: reboot

  storage:
    config:
      - type: disk
        id: disk0
        match:
          size: largest
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        grub_device: false
      
      - type: partition
        id: partition-efi
        device: disk0
        size: 1G
        flag: boot
        number: 1
        preserve: false
        grub_device: true
      
      - type: partition
        id: partition-boot
        device: disk0
        size: 2G
        number: 2
        preserve: false
      
      - type: partition
        id: partition-main
        device: disk0
        size: -1
        number: 3
        preserve: false
      
      - type: dm_crypt
        id: dm-crypt-main
        dm_name: dm_crypt-main  # Explicitly set the mapper name
        volume: partition-main
        key: "ubuntuKey"
        preserve: false
      
      - type: lvm_volgroup
        id: vg0
        name: ubuntu-vg
        devices:
          - dm-crypt-main
        preserve: false
      
      - type: lvm_partition
        id: lv-swap
        volgroup: vg0
        name: swap
        size: 8G
        preserve: false
      
      - type: lvm_partition
        id: lv-root
        volgroup: vg0
        name: root
        size: -1
        preserve: false
      
      - type: format
        id: fs-efi
        volume: partition-efi
        fstype: vfat
        preserve: false
      
      - type: format
        id: fs-boot
        volume: partition-boot
        fstype: ext4
        preserve: false
      
      - type: format
        id: fs-root
        volume: lv-root
        fstype: ext4
        preserve: false
      
      - type: format
        id: fs-swap
        volume: lv-swap
        fstype: swap
        preserve: false
      
      - type: mount
        id: mount-root
        device: fs-root
        path: /
      
      - type: mount
        id: mount-boot
        device: fs-boot
        path: /boot
      
      - type: mount
        id: mount-efi
        device: fs-efi
        path: /boot/efi
      
      - type: mount
        id: mount-swap
        device: fs-swap
        path: none
  
  packages:
    - cryptsetup-initramfs
    - cryptsetup-bin
